apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-db-dp
  namespace: storage-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-db
  template:
    metadata:
      name: storage-db-pod
      labels:
        app: storage-db
    spec:
      containers:
        - name: storage-db
          image: mongo:4.4
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: storage-db-cm
                  key: user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: storage-db-cm
                  key: password
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 27017
