apiVersion: v1
kind: Service
metadata:
  name: gateway-api-svc
  namespace: storage-ns
spec:
  type: NodePort
  selector:
    app: gateway-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
