apiVersion: v1
kind: Service
metadata:
  name: storage-api-svc
  namespace: storage-ns
spec:
  type: ClusterIP
  selector:
    app: storage-api
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
